<?php

namespace AppBundle\Repository;

/**
 * CarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllCarsByMake(string $make){
        return $this
            ->createQueryBuilder('car')
            ->where('car.make', ':make')
            ->setParameter('make', $make)
            ->orderBy('car.model', 'asc')
            ->orderBy('car.travelledDistance', 'desc')
            ->getQuery()
            ->getResult();
    }
}
