<?php

namespace AppBundle\Repository;

/**
 * SupplierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SupplierRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllSuppliersByType(string $type){
        $isImporter = $type != 'local';

        return $this
            ->createQueryBuilder('supplier')
            ->where('supplier.isImporter', ':isImporter')
            ->setParameter('isImporter', $isImporter)
            ->getQuery()
            ->getResult();
    }
}
